const exampleMetadata = [
  {
    title: 'Beautiful (Original Vocal Mix)',
    artist: 'Para X & Claire Willis',
    album: 'Beautiful',
    genre: 'Trance',
    comment: '',
    label: 'Discover Records (UK)',
    year: '2018',
    key: '02A',
  },
  {
    title: 'Addict (Pulse Remix)',
    artist: 'S3RL',
    album: 'The Big 100: Addict Remixes EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2013',
    key: '01A',
  },
  {
    title: 'Psymbiosis Blistering (Breaks Mix)',
    artist: 'Ephexis & Seventy-7',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '12B',
  },
  {
    title: 'Show Me The Way (Squad-E Remix)',
    artist: 'Hypasonic Ft. Davey B',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Twista Records',
    year: '2012',
    key: '02A',
  },
  {
    title: 'Rest Of Your Life',
    artist: 'Darren Styles & Re-Con Ft. Matthew Steeper',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Together We Rise',
    year: '2015',
    key: '10A',
  },
  {
    title: 'Move With You',
    artist: 'S3RL Ft. JessKah',
    album: 'The S3RL Digital EP 3',
    genre: 'Hardcore',
    comment: '',
    label: 'Executive Digital',
    year: '2009',
    key: '03A',
  },
  {
    title: 'Escape The Asylum (NG Rezonance Reprise)',
    artist: 'Guyver',
    album: 'Escape The Asylum',
    genre: 'Hard Trance',
    comment: '',
    label: 'Metamorph Rapture',
    year: '2013',
    key: '10A',
  },
  {
    title: 'Summer Rain (Matt Hylo Remix)',
    artist: 'Starstruck Ft. Gemma',
    album: 'Summer Rain EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '07B',
  },
  {
    title: 'Sweet Release (Original Mix)',
    artist: 'Antix & Tom-E',
    album: 'Sweet Release / In My Eyes',
    genre: 'Hardcore',
    comment: '',
    label: 'Executive Records',
    year: '2005',
    key: '07A',
  },
  {
    title: 'Llamacore',
    artist: 'Camzor & Interlude',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '08A',
  },
  {
    title: "Think We're Alone Now",
    artist: 'Touch',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Jump 4 Joy',
    year: '2015',
    key: '10B',
  },
  {
    title: 'Around The World',
    artist: 'Block-E',
    album: 'Hardcore Producer Vol.2: The Future of Hardcore',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '05A',
  },
  {
    title: 'Break Up (Technikore 2013 Remix)',
    artist: 'Kim Sozzi',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2014',
    key: '07A',
  },
  {
    title: 'Endless',
    artist: 'Factor B',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Pure Trance',
    year: '2016',
    key: '08A',
  },
  {
    title: 'Dance With Drugs',
    artist: 'DJ Versatile',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '01A',
  },
  {
    title: 'Oyasumi (TANUKI & Dil Remix)',
    artist: 'kors k Ft. Sunao Yoshikawa',
    album: 'HARDCORE UNITED TOKYO',
    genre: 'Hardcore',
    comment: '',
    label: 'S2TB Recording',
    year: '2013',
    key: '01B',
  },
  {
    title: 'When The Rain Comes',
    artist: 'The Acolyte Ft. Amy',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'FutureNoize',
    year: '2006',
    key: '07A',
  },
  {
    title: 'Attack The Dance Floor',
    artist: 'Bishop',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '10A',
  },
  {
    title: 'Dance (Damaged Remix)',
    artist: 'Apollo',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Envious Hardcore',
    year: '2010',
    key: '11B',
  },
  {
    title: 'Bakanbetanbitendrag',
    artist: 'Daniel Seven & Nakura',
    album: 'RuffBeatz: Hardcore Resistance',
    genre: 'Hardcore',
    comment: '',
    label: 'RuffBeatz',
    year: '2012',
    key: '11A',
  },
  {
    title: "Can't Compete",
    artist: 'Gammer',
    album: "Can't Compete / Rippin Up",
    genre: 'Freeform',
    comment: '',
    label: 'Relentless Vinyl',
    year: '2004',
    key: '06B',
  },
  {
    title: 'Turn The Tide (Darren Styles Remix)',
    artist: 'Manian',
    album: 'Welcome To The Club / Turn The Tide (Darren Styles Mixes)',
    genre: 'Hardcore',
    comment: '',
    label: 'Junkbox',
    year: '2010',
    key: '08A',
  },
  {
    title: 'Flawless Victory',
    artist: 'Substanced & J-Mx',
    album: 'When The World Collapses',
    genre: 'Freeform',
    comment: '',
    label: 'FINRG Recordings',
    year: '2012',
    key: '07A',
  },
  {
    title: 'The Voice',
    artist: 'DJ Kurt vs Trax Ft. Sara',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '08A',
  },
  {
    title: 'Techno Wonderland 2007 (S3RL Remix)',
    artist: 'Splash vs Vibes',
    album: 'Techno Wonderland 2007',
    genre: 'Hardcore',
    comment: '',
    label: 'Liquid Hardcore',
    year: '2008',
    key: '03A',
  },
  {
    title: 'Show Me',
    artist: 'Technikore',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '10B',
  },
  {
    title: 'Turn Back Time',
    artist: 'Fracus & Darwin',
    album: 'Point of No Return',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2012',
    key: '10B',
  },
  {
    title: 'Fall To Pieces (Daniel Skyver Remix)',
    artist: 'Jonas Steur Ft. Jennifer Rene',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Grotesque Reworked',
    year: '2018',
    key: '05A',
  },
  {
    title: 'Under Pressure',
    artist: 'Darwin & Cube::Hard',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Just Another Label',
    year: '2007',
    key: '12A',
  },
  {
    title: 'Rippin Up',
    artist: 'Gammer',
    album: "Can't Compete / Rippin Up",
    genre: 'Freeform',
    comment: '',
    label: 'Relentless Vinyl',
    year: '2004',
    key: '06A',
  },
  {
    title: 'Good Night',
    artist: 'S3RL Ft. Wendy',
    album: 'Hardcore Energy 2',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '07A',
  },
  {
    title: 'One For Me',
    artist: 'DNC & Mansy',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '11B',
  },
  {
    title: 'The Perfect Storm (Extended Mix)',
    artist: 'Sue McLaren & Stargazers',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Ellicit Music (RazNitzanMusic)',
    year: '2018',
    key: '03A',
  },
  {
    title: "Breakin' Thru (DJ Shimamura Remix)",
    artist: 'Bang! vs Al Storm Ft. Niki Mak',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '24/7 Hardcore',
    year: '2016',
    key: '02B',
  },
  {
    title: 'Illuminated',
    artist: 'Nu Foundation',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '08B',
  },
  {
    title: 'Talk vs Clarity (DJ Perihelion Mashup)',
    artist: 'Darren Styles vs Zedd',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2014',
    key: '05B',
  },
  {
    title: "Rockin'",
    artist: 'Damaged & Xecuted',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '11B',
  },
  {
    title: 'Drifting Away (Alessandra Roncone Bootleg)',
    artist: 'Lange',
    album: '',
    genre: 'Trance',
    comment: '',
    label: '',
    year: '2016',
    key: '09A',
  },
  {
    title: 'Over The Rainbow',
    artist: 'Miroslav Vrlik',
    album: 'Over The Rainbow',
    genre: 'Trance',
    comment: '',
    label: 'Amon Vision',
    year: '2020',
    key: '09B',
  },
  {
    title: 'Fade Away',
    artist: 'Darwin',
    album: 'Hardcore Underground EP Vol. 3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2013',
    key: '08A',
  },
  {
    title: 'Hardcore Life (Original Mix)',
    artist: 'S3RL & Mc Gremlin Ft. Kimberley',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Ravin Records',
    year: '2011',
    key: '11B',
  },
  {
    title: 'Skywalker',
    artist: 'Jnks',
    album: 'Crush On Hardcore: Sequel Of The V',
    genre: 'Hardcore',
    comment: '',
    label: 'Crush On',
    year: '2010',
    key: '01B',
  },
  {
    title: 'Show Me',
    artist: 'Technikore Ft. Nathalie',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '10B',
  },
  {
    title: 'Disconnected',
    artist: 'Helblinde',
    album: '',
    genre: 'Freeform',
    comment: '',
    label: '',
    year: '2012',
    key: '07A',
  },
  {
    title: 'Fallen',
    artist: 'Rhythmics',
    album: 'Welp',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '03A',
  },
  {
    title: 'More Important Things',
    artist: 'Custom Built DJs',
    album: 'RuffBeatz & Freeformaniacs - Freeformatted',
    genre: 'Freeform',
    comment: '',
    label: 'RuffBeatz',
    year: '2012',
    key: '06A',
  },
  {
    title: 'Breath Again',
    artist: 'Impact',
    album: 'Breath Again / Shine On Me',
    genre: 'Hardcore',
    comment: '',
    label: 'MasterWax Records',
    year: '2006',
    key: '03B',
  },
  {
    title: 'Nothing There (Reese Remix)',
    artist: 'Chwhynny & Darwin',
    album: 'Nothing There',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2010',
    key: '06A',
  },
  {
    title: 'In My Eyes (Dover Remix)',
    artist: 'Antix & Tom-E',
    album: 'Sunrise / In My Eyes / Street Fighter / Higher & Higher',
    genre: 'Hardcore',
    comment: '',
    label: 'Executive Records',
    year: '2010',
    key: '08A',
  },
  {
    title: 'Tranny Stream',
    artist: 'Ryu☆',
    album: 'HARDCORE UNITED TOKYO',
    genre: 'Hardcore',
    comment: '',
    label: 'S2TB Recording',
    year: '2013',
    key: '01A',
  },
  {
    title: 'The Rock Show',
    artist: 'Starstruck',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2009',
    key: '11B',
  },
  {
    title: 'Guitar Hero (Kors K) x Anybody Else But You (Bad Corey Mash Up)',
    artist: 'Kors K x Dougal & Gammer',
    album: 'Guitar Hero Mash Up EP',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '08B',
  },
  {
    title: 'The World In My Eyes',
    artist: 'The Mechanic & Vindicator',
    album: 'The World In My Eyes',
    genre: 'Trance',
    comment: '',
    label: 'VERSE (Equinox)',
    year: '2019',
    key: '09B',
  },
  {
    title: 'Rebuild Your Heart (Weaver Mix)',
    artist: 'Robert Francis & Andy L',
    album: 'Rebuild Your Heart',
    genre: 'Hardcore',
    comment: '',
    label: 'Evolution Records',
    year: '2009',
    key: '11A',
  },
  {
    title: 'Freedom',
    artist: 'Kyla, Fracus & Darwin',
    album: 'Balancing Act',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2012',
    key: '06B',
  },
  {
    title: 'Exploration Of Space',
    artist: 'Cosmic Gate vs Skeets',
    album: 'Hardcore Producer Vol.2: The Future of Hardcore',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '08A',
  },
  {
    title: 'Hardcore Shockwave',
    artist: 'Hommarju Ft. MK',
    album: 'We R Relentless Presents The Best Of X-FIR3',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '11A',
  },
  {
    title: 'This Is The Place (Kevin Energy Remix)',
    artist: 'Kevin Energy & Gammer',
    album: 'Hardcore Energy',
    genre: 'Freeform',
    comment: '',
    label: 'Can You Feel It Media',
    year: '2010',
    key: '08A',
  },
  {
    title: 'Lonely Inside (Extended Ferry Fix)',
    artist: 'Ferry Corsten',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Flashover Recordings',
    year: '2017',
    key: '08A',
  },
  {
    title: 'Seismic Activity (Transcend Remix)',
    artist: 'Substanced',
    album: 'When The World Collapses',
    genre: 'Freeform',
    comment: '',
    label: 'FINRG Recordings',
    year: '2012',
    key: '07B',
  },
  {
    title: 'Still Alive',
    artist: 'Aethral',
    album: '',
    genre: 'Freeform',
    comment: '',
    label: '',
    year: '2014',
    key: '02A',
  },
  {
    title: 'Stickerbrush Synthphony',
    artist: 'raz.',
    album: 're:BOOTed',
    genre: 'Ambient',
    comment: '',
    label: '',
    year: '2014',
    key: '08B',
  },
  {
    title: 'Extra Terrestrial',
    artist: 'Defekt & Kay Pez',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Original Hardcore',
    year: '2011',
    key: '04A',
  },
  {
    title: 'Promised Land (Squad-E Remix)',
    artist: 'Access 3',
    album: 'Squad-E Remixes',
    genre: 'Hardcore',
    comment: '',
    label: 'Raver Baby',
    year: '2006',
    key: '09A',
  },
  {
    title: 'Raindrops (Damaged & Krays Remix)',
    artist: 'Sash Ft. Stunt',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Envious Hardcore',
    year: '2010',
    key: '10A',
  },
  {
    title: 'Glacier',
    artist: 'Zekk vs Awfuless',
    album: 'Above The World II',
    genre: 'Hardcore',
    comment: '',
    label: 'PAO-WHO Records',
    year: '2016',
    key: '10A',
  },
  {
    title: 'Sunray Unfinished Forever',
    artist: 'Alek Száhala',
    album: 'Crush On Hardcore: Sequel Of The V',
    genre: 'Hardcore',
    comment: '',
    label: 'Crush On',
    year: '2010',
    key: '06B',
  },
  {
    title: "Rushin'",
    artist: 'DJ Shimamura',
    album: 'VORTEX',
    genre: 'Hardcore',
    comment: '',
    label: 'Dynasty Records',
    year: '2018',
    key: '09A',
  },
  {
    title: 'Linkshop',
    artist: 'Audien',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2008',
    key: '08B',
  },
  {
    title: 'White Hood',
    artist: 'Kiyoi & Eky',
    album: 'White Hood',
    genre: 'Trance',
    comment: '',
    label: 'Tranceform',
    year: '2017',
    key: '07A',
  },
  {
    title: 'How Do You Do',
    artist: 'DJ Triex',
    album: 'RuffBeatz: Hardcore Resistance',
    genre: 'Hardcore',
    comment: '',
    label: 'RuffBeatz',
    year: '2012',
    key: '05A',
  },
  {
    title: 'All My Life',
    artist: 'Rising Star Ft. Marie Louise',
    album: 'Rising Star EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Executive Records',
    year: '2010',
    key: '05B',
  },
  {
    title: 'Welcome',
    artist: 'Ranzor',
    album: 're:BOOTed',
    genre: 'TBD',
    comment: '',
    label: '',
    year: '2014',
    key: '05A',
  },
  {
    title: 'The Baptism (A.B & Amplitude Remix)',
    artist: 'Kevin Energy & Safe N Sound',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '08A',
  },
  {
    title: 'The Power Of Love (Extended Mix)',
    artist: 'Misja Helsloot, XiJaro & Pitch, Cari',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'In Trance We Trust',
    year: '2019',
    key: '09B',
  },
  {
    title: 'Cape Reinga',
    artist: 'Tolland, Kayosa, Matt Noland',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Titan Audio',
    year: '2018',
    key: '10B',
  },
  {
    title: 'Hardcore Toccata',
    artist: 'Kevin Energy & The Ultimate Raver',
    album: 'Hardcore Energy',
    genre: 'Freeform',
    comment: '',
    label: 'Can You Feel It Media',
    year: '2010',
    key: '08A',
  },
  {
    title: 'See You On The Other Side (Douglas Remix)',
    artist: 'CLSM & Cube::Hard',
    album: 'See You On The Other Side',
    genre: 'Freeform',
    comment: '',
    label: 'G-Core',
    year: '2012',
    key: '04A',
  },
  {
    title: 'Magic Rave Night',
    artist: 'DJ Noriken & MC Stone',
    album: 'HARDCORE UNITED TOKYO',
    genre: 'Hardcore',
    comment: '',
    label: 'S2TB Recording',
    year: '2013',
    key: '07A',
  },
  {
    title: 'Back 2 Nature',
    artist: 'H-Blast Energetix',
    album: 'RuffBeatz & Freeformaniacs - Freeformatted',
    genre: 'Freeform',
    comment: '',
    label: 'RuffBeatz',
    year: '2012',
    key: '10B',
  },
  {
    title: 'Release The Fear (Exclusive Intro Mix)',
    artist: 'Kevin Energy & Nick 235 Ft. Rhona',
    album: 'Hardcore Energy',
    genre: 'Freeform',
    comment: '',
    label: 'Can You Feel It Media',
    year: '2010',
    key: '08B',
  },
  {
    title: 'Shine On Me',
    artist: 'Impact',
    album: 'Breath Again / Shine On Me',
    genre: 'Hardcore',
    comment: '',
    label: 'MasterWax Records',
    year: '2006',
    key: '05B',
  },
  {
    title: 'Massiah (Re-Con & Chris Unknown Remix)',
    artist: 'I See Monstas',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2015',
    key: '05A',
  },
  {
    title: 'Bounce',
    artist: 'X-FIR3 & Sensation',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '01A',
  },
  {
    title: 'Right Back (Solis & Sean Truby Extended Remix)',
    artist: 'Yuri Kane',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Flashover Trance',
    year: '2018',
    key: '09A',
  },
  {
    title: "Wherever I'll Be",
    artist: 'New World & Di Bauer',
    album: "Wherever I'll Be",
    genre: 'Trance',
    comment: '',
    label: 'Defcon Recordings',
    year: '2018',
    key: '06B',
  },
  {
    title: 'Deeper Still (Oh Right)',
    artist: 'Stabilize',
    album: 'We R Relentless Presents The Best Of X-FIR3',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '10B',
  },
  {
    title: 'Falling Over The Moon',
    artist: 'Starstruck & Influx  Ft. Zuraya Hamilton',
    album: 'Falling Over The Moon',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2009',
    key: '11B',
  },
  {
    title: 'WipeOut (RePlastered Mix)',
    artist: 'X-FIR3',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2013',
    key: '07A',
  },
  {
    title: 'Fly Away (Now) (Eufeion Hardcore Bootleg)',
    artist: 'Panty & Stocking',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2014',
    key: '12A',
  },
  {
    title: 'Raindrops',
    artist: 'Inverse & Evolution',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'FutureNoize',
    year: '2008',
    key: '10A',
  },
  {
    title: 'Outro',
    artist: 'XIO',
    album: 'Asgard',
    genre: 'Freeform',
    comment: '',
    label: 'Japanese With Force',
    year: '2012',
    key: '02B',
  },
  {
    title: 'Dream (Eryk Orpheus Remix)',
    artist: "Two's Company",
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '05A',
  },
  {
    title: 'Milestone',
    artist: 'Rhythmics',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Magic Chord',
    year: '2013',
    key: '03A',
  },
  {
    title: 'Born Again (Breeze & Styles Remix)',
    artist: 'Enlighten',
    album: 'Born Again',
    genre: 'Hardcore',
    comment: '',
    label: 'Quosh Records',
    year: '2004',
    key: '08A',
  },
  {
    title: 'New Heights (2012 Mix)',
    artist: 'Cat Like Thief',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2014',
    key: '10B',
  },
  {
    title: 'Mental Atmosphere',
    artist: 'Technikore',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '11A',
  },
  {
    title: 'How Can I (James Dymond Remix)',
    artist: 'Craig Connelly Ft. Jessica Lawrence',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Higher Forces Records',
    year: '2017',
    key: '08A',
  },
  {
    title: 'Everything (Elliot X-Ell Remix',
    artist: 'Gaz-V',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2015',
    key: '05B',
  },
  {
    title: 'What A Feeling ',
    artist: 'Rising Star Ft. Marie Louise',
    album: 'Your Love Is My Drug / What A Feeling',
    genre: 'Hardcore',
    comment: '',
    label: 'Recycled Records',
    year: '2011',
    key: '06A',
  },
  {
    title: 'Give Me More',
    artist: 'Audien Ft. Cotts',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2008',
    key: '08A',
  },
  {
    title: 'Adagio',
    artist: 'Darwin',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Just Another Label',
    year: '2006',
    key: '08A',
  },
  {
    title: 'Forever and a Day',
    artist: 'Ram, Stine Grove Ft. Stine Grove',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Grotesque',
    year: '2016',
    key: '04A',
  },
  {
    title: 'Not Over (Exclusive)',
    artist: 'Lucky Strike',
    album: 'Hardcore Producer Vol.1: Remixed',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2010',
    key: '09B',
  },
  {
    title: 'Rising Like The Sun',
    artist: 'Gisbo',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Tryed N Tested',
    year: '2010',
    key: '01B',
  },
  {
    title: 'Rock This (Archefluxx Remix)',
    artist: 'Ozmium',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2010',
    key: '03B',
  },
  {
    title: 'Systemization (Ranzor Remix)',
    artist: 'Archefluxx',
    album: 'Touitsu Compilation Vol.1',
    genre: 'Hardcore',
    comment: '',
    label: 'Touitsu Recordings',
    year: '2013',
    key: '06B',
  },
  {
    title: 'Coming Up (Kevin Energy Hard Remix)',
    artist: 'A.B',
    album: 'Hardcore Energy',
    genre: 'Freeform',
    comment: '',
    label: 'Can You Feel It Media',
    year: '2010',
    key: '08A',
  },
  {
    title: 'Know What It Takes',
    artist: 'Fracus & Darwin Ft. Jeston Langland',
    album: 'Filth And Dumb Hatred',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2014',
    key: '11B',
  },
  {
    title: 'Ultimate Affection',
    artist: '3R2',
    album: 'RuffBeatz: Audio Crysis',
    genre: 'Hardcore',
    comment: '',
    label: 'RuffBeatz',
    year: '2011',
    key: '07A',
  },
  {
    title: "Now I'm Free",
    artist: 'Fracus & Darwin',
    album: 'Balancing Act',
    genre: 'Drum & Bass',
    comment: '',
    label: 'Hardcore Underground',
    year: '2012',
    key: '03A',
  },
  {
    title: 'Dysnomia (Extended Mix)',
    artist: 'N-sKing',
    album: 'Dysnomia',
    genre: 'Trance',
    comment: '',
    label: 'Beyond The Stars Recordings',
    year: '2020',
    key: '07A',
  },
  {
    title: 'Far Away',
    artist: 'Rhythmics',
    album: 'Welp',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '04B',
  },
  {
    title: 'Fallen',
    artist: 'Technikore & MOB',
    album: 'Hardcore Innovators 2',
    genre: 'Hardcore',
    comment: '',
    label: 'Lethal Theory',
    year: '2014',
    key: '12B',
  },
  {
    title: 'Promise You (Maria Healy Extended Remix)',
    artist: 'Fast Distance, Cami, DIM3NSION',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Always Alive Recordings',
    year: '2019',
    key: '02B',
  },
  {
    title: "Don't Hold Ya Breath (Exclusive Vocal Mix)",
    artist: 'Kurt',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '05A',
  },
  {
    title: 'Tormenting Flames',
    artist: 'Transcend & Dyzphazia',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '01A',
  },
  {
    title: 'Language (Kayzo & Gammer Remix)',
    artist: 'Porter Robinson',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2016',
    key: '11B',
  },
  {
    title: 'Stimulate',
    artist: 'Alex Sash',
    album: 'Crush On Hardcore: Sequel Of The V',
    genre: 'Hardcore',
    comment: '',
    label: 'Crush On',
    year: '2010',
    key: '05A',
  },
  {
    title: "Davey's Song",
    artist: 'Spins & DJ HARN',
    album: "Davey's Song",
    genre: 'Trance',
    comment: '',
    label: 'Digitized Recordings',
    year: '2017',
    key: '06B',
  },
  {
    title: 'WoWoWoW (Hutchy Remix)',
    artist: 'Sparkz',
    album: 'Hardcore Producer Vol.2: The Future of Hardcore',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '06B',
  },
  {
    title: 'Paranoid',
    artist: 'Kevin Energy Ft. MC Static',
    album: 'Hardcore Energy',
    genre: 'Freeform',
    comment: '',
    label: 'Can You Feel It Media',
    year: '2010',
    key: '10A',
  },
  {
    title: 'Cry',
    artist: 'Starstruck',
    album: 'Cry - The Final EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '08B',
  },
  {
    title: 'My Direction (Squad-E Remix)',
    artist: 'D:CODE',
    album: 'My Direction',
    genre: 'Hardcore',
    comment: '',
    label: 'All Around The World',
    year: '2007',
    key: '09A',
  },
  {
    title: 'Safe & Sound x Guitar Hero (Bad Corey Mash Up)',
    artist: 'Chris Ross x Technikore',
    album: 'Guitar Hero Mash Up EP',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '08B',
  },
  {
    title: 'ROMANTIC CHILDREN',
    artist: 'Babbe',
    album: 'Lucky Lotus Volume 1',
    genre: 'Trance',
    comment: '',
    label: 'Lucky Lotus Records',
    year: '2014',
    key: '06A',
  },
  {
    title: "Lookin' Like That",
    artist: 'Señor Hotdog',
    album: 'Influx vs Señor Hotdog EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '12B',
  },
  {
    title: 'The Way (Chaos Mix)',
    artist: 'Divine Inspiration',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2012',
    key: '08B',
  },
  {
    title: 'Beautiful Monster (Gisbo Remix)',
    artist: 'Neyo',
    album: 'Gisbo Promotional Album',
    genre: 'Hardcore',
    comment: '',
    label: 'In Your Head Records',
    year: '2011',
    key: '04A',
  },
  {
    title: 'True Believer (Styles & Breeze Remix)',
    artist: 'E-Type',
    album: 'True Believer / Rain (Styles & Breeze Mixes)',
    genre: 'Hardcore',
    comment: '',
    label: 'Junkbox',
    year: '2010',
    key: '03A',
  },
  {
    title: 'PVC (Lost Soul Remix)',
    artist: 'Eryk Orpheus',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '08A',
  },
  {
    title: 'The Realm',
    artist: 'Orbit1',
    album: 'The Realm / Project.1',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '12B',
  },
  {
    title: 'Everytime We Say Goodbye (Technikore Remix)',
    artist: 'Al Storm Ft. Malaya',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '24/7 Hardcore',
    year: '2011',
    key: '12B',
  },
  {
    title: 'PLUR',
    artist: 'Auscore',
    album: 'The Auscore EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2009',
    key: '05B',
  },
  {
    title: 'Heaven (Gammer Remix)',
    artist: 'Nukleuz Kollective',
    album: 'Nukleuz Hardcore EP 10 Bootleg Edition',
    genre: 'Hardcore',
    comment: '',
    label: 'Nukleuz',
    year: '2007',
    key: '05B',
  },
  {
    title: 'Lopiszsk',
    artist: 'Audien & Naggy',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2008',
    key: '03A',
  },
  {
    title: 'Love Sick Crazy',
    artist: 'Styles & Breeze Ft. Re-Con',
    album: 'Love Sick Crazy',
    genre: 'Hardcore',
    comment: '',
    label: 'Futureworld',
    year: '2009',
    key: '06A',
  },
  {
    title: '5Th Dimension',
    artist: 'Ranzor',
    album: 'Summer Warm Up EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '09A',
  },
  {
    title: 'Body Bag',
    artist: 'DJ Kurt vs Nizzle & MPH',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '11B',
  },
  {
    title: 'Dark Heart',
    artist: 'Kurt vs Noizy Boiz',
    album: "Feel Complete / We're Gonna Rock You / Dark Heart / Teeh Grinder",
    genre: 'Hardcore',
    comment: '',
    label: 'Lethal Theory',
    year: '2011',
    key: '10A',
  },
  {
    title: "Don't Be Afraid",
    artist: 'Dan Edge & Ben Manic',
    album: 'Scarred Digital: The Best Of 2018',
    genre: 'Hardcore',
    comment: '',
    label: 'Scarred Digital',
    year: '2018',
    key: '10A',
  },
  {
    title: 'Shooting Star (Falcore Remix)',
    artist: 'Bang!',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2015',
    key: '03A',
  },
  {
    title: 'The Rock Show (2010 Mix)',
    artist: 'Starstruck',
    album: 'The Rock Show Remix EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '11B',
  },
  {
    title: 'Met U On The Dancefloor (Instrumental Mix)',
    artist: 'Zero-2 & Starstruck',
    album: 'The Brisbane Hardcore EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '02B',
  },
  {
    title: 'Hold Me Tonight (Re-Con Remix)',
    artist: 'Manian',
    album: 'Piece of Heaven / Hold Me Tonight',
    genre: 'Hardcore',
    comment: '',
    label: 'Twista Records',
    year: '2010',
    key: '05A',
  },
  {
    title: "Takin' Me Higher (Doofus da Dingo's Donk Remix)",
    artist: 'Darren Styles',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '03B',
  },
  {
    title: 'Psystyler',
    artist: 'Nova & Ganah',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Evolution Records',
    year: '2018',
    key: '04A',
  },
  {
    title: 'The Power Within 2011',
    artist: 'Joey Riot Ft. Kelly C',
    album:
      "I'll Be Your Lover / Kevin And Perry Go Ravin / The Power Within 2010 / Speaker Check",
    genre: 'Hardcore',
    comment: '',
    label: 'Lethal Theory',
    year: '2011',
    key: '04A',
  },
  {
    title: 'Since You Went Away',
    artist: 'Brisk & Ham Ft. Sarah Jane',
    album:
      "Since You Went Away / Dance Don't Slip / Fire & Flames (Nu Foundation & Haywire Remix)",
    genre: 'Hardcore',
    comment: '',
    label: 'Next Generation',
    year: '2011',
    key: '12A',
  },
  {
    title: 'Sahara',
    artist: 'Lumin8 & Cheever',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'FutureNoize',
    year: '2008',
    key: '10B',
  },
  {
    title: 'The Happy Tune! (Big Kick Mix)',
    artist: 'Spirit Wolf',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '03B',
  },
  {
    title: 'Against The World (Ganar Remix)',
    artist: 'Morgan Page & Michael S.',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'G Records',
    year: '2014',
    key: '08B',
  },
  {
    title: 'Crazy Pillz',
    artist: 'Firefly vs Pulse',
    album: 'RuffBeatz & Freeformaniacs - Freeformatted',
    genre: 'Freeform',
    comment: '',
    label: 'RuffBeatz',
    year: '2012',
    key: '01A',
  },
  {
    title: 'Naiad (Extended Mix)',
    artist: 'Kiyoi & Eky, Khairy Ahmed',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Digital Society Recordings',
    year: '2019',
    key: '08A',
  },
  {
    title: 'Beyond The Sun',
    artist: 'Claire Willis & Infinity X',
    album: 'Beyond The Sun',
    genre: 'Trance',
    comment: '',
    label: 'Arkham Digital',
    year: '2018',
    key: '08B',
  },
  {
    title: 'Orbit2000',
    artist: 'Orbit1',
    album: 'Orbit1 EP #2',
    genre: 'Hardcore',
    comment: '',
    label: 'Australia With Force',
    year: '2010',
    key: '11A',
  },
  {
    title: 'Follow The Light',
    artist: 'Flawless & Bananaman Ft. Dahni-Bria',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Jump 4 Joy',
    year: '2014',
    key: '06A',
  },
  {
    title: 'Hard To Find',
    artist: 'Fracus & Darwin',
    album: 'Point of No Return',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2012',
    key: '03B',
  },
  {
    title: 'Hasta Mañana',
    artist: 'Al Storm & Euphony Ft. Mandy Edge',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '24/7 Hardcore',
    year: '2016',
    key: '02A',
  },
  {
    title: 'Reckless',
    artist: 'Hutchy',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '08A',
  },
  {
    title: 'Take Me Away (Darren G & Bridson Remix)',
    artist: 'Bridson & DNC Ft. Becki',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Rave Essentials',
    year: '2016',
    key: '06B',
  },
  {
    title: 'Man On The Moon',
    artist: 'Audio Warfare',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Audio Weaponry',
    year: '2011',
    key: '08A',
  },
  {
    title: 'Devastator',
    artist: 'Eclipse',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '07B',
  },
  {
    title: 'Lose Control',
    artist: 'Eufeion, Denile, Hannah Stacia',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Ninja Hardcore',
    year: '2017',
    key: '11A',
  },
  {
    title: 'Rainbow Girl (Candlelight Mix)',
    artist: 'S3RL Ft. Tamika',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'EMFA Music',
    year: '2015',
    key: '04B',
  },
  {
    title: 'Egao no Kimi e (Sharpmarker Edit)',
    artist: 'Suzuko Mimori',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2017',
    key: '07B',
  },
  {
    title: 'Together (SynthWulf Remix)',
    artist: 'Dancelordz',
    album: '',
    genre: 'Freeform',
    comment: '',
    label: 'Relentless Energy',
    year: '2010',
    key: '08A',
  },
  {
    title: "Don't Forget",
    artist: 'Audien',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2008',
    key: '11A',
  },
  {
    title: 'Draw To You',
    artist: 'The Acolyte Ft. Amy',
    album: 'Dusk Till Dawn - The Complete Works',
    genre: 'Hardcore',
    comment: '',
    label: 'Electronica Exposed',
    year: '2008',
    key: '01A',
  },
  {
    title: 'Raise Ur Hands (Eufeion Remix)',
    artist: 'DJ Robbo',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Electrik Euphoria',
    year: '2010',
    key: '08A',
  },
  {
    title: 'Rocket',
    artist: 'Audien',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2009',
    key: '05A',
  },
  {
    title: 'Outta My Head (Nakura Remix)',
    artist: 'Darren Styles',
    album: 'Hardcore Producer Vol.2: The Future of Hardcore',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '01B',
  },
  {
    title: 'Satellite (Update)',
    artist: 'Darren Styles',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Futureworld',
    year: '2013',
    key: '01B',
  },
  {
    title: 'Falling',
    artist: 'Kracy & Compressor',
    album: 'Musik Box Anthem 2013',
    genre: 'Hardcore',
    comment: '',
    label: 'Musik Box',
    year: '2013',
    key: '08A',
  },
  {
    title: "You're The One (Olly P Remix)",
    artist: 'Gisbo Ft. Kellyyx',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2013',
    key: '09B',
  },
  {
    title: 'Are You Ready',
    artist: 'Gregor Le DahL',
    album: 'Summer Warm Up EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Relentless Digital',
    year: '2012',
    key: '10A',
  },
  {
    title: 'Eternal Cannon (DJ Rx Remix)',
    artist: 'RaverRose & Thermal Force',
    album: 'Crush On Hardcore: Sequel Of The V',
    genre: 'Hardcore',
    comment: '',
    label: 'Crush On',
    year: '2010',
    key: '02A',
  },
  {
    title: 'Everafter',
    artist: 'Chasers',
    album: '',
    genre: 'Hard Trance',
    comment: '',
    label: '',
    year: '2013',
    key: '04B',
  },
  {
    title: 'The Last Word (Sam Laxton Remix)',
    artist: 'Sheridan Grout',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'AVA White',
    year: '2017',
    key: '02A',
  },
  {
    title: 'You Can (Not) Love',
    artist: 'Charger',
    album: 'Touitsu Compilation Vol.1',
    genre: 'Hardcore',
    comment: '',
    label: 'Touitsu Recordings',
    year: '2013',
    key: '07B',
  },
  {
    title: "Don't Leave Me Now (Darren Styles Remix)",
    artist: 'Unknown & Sy Ft. Lou Lou',
    album: "Don't Leave Me Now",
    genre: 'Hardcore',
    comment: '',
    label: 'Quosh Records',
    year: '2008',
    key: '05A',
  },
  {
    title: "Rock This Place (Damaged's Short N Sweet Mix)",
    artist: 'Nakura',
    album: 'Hardcore Producer Vol.3',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Producer',
    year: '2011',
    key: '11A',
  },
  {
    title: 'I Miss You',
    artist: 'Nu Foundation',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '03B',
  },
  {
    title: 'Six Stolen Kisses (Extended Mix)',
    artist: 'Adam Ellis & Charles Tsai',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Ellicit Music (RazNitzanMusic)',
    year: '2020',
    key: '07A',
  },
  {
    title: 'New Life',
    artist: 'Tau-Rine',
    album: 'New Life',
    genre: 'Trance',
    comment: '',
    label: 'Taurine Music',
    year: '2017',
    key: '04A',
  },
  {
    title: 'Crazy For Your Love',
    artist: 'Fracus & Darwin vs Michael Mansion',
    album: 'Filth And Dumb Hatred',
    genre: 'Hardcore',
    comment: '',
    label: 'Hardcore Underground',
    year: '2014',
    key: '12B',
  },
  {
    title: 'Worldwide (CubeHard Remix)',
    artist: 'Ponder',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Whojamaflip',
    year: '2007',
    key: '09A',
  },
  {
    title: 'Elysium (Cat Like Thief Remix)',
    artist: 'Scott Brown',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2014',
    key: '05B',
  },
  {
    title: 'See The Light (Gammer Remix)',
    artist: 'Paradise',
    album: 'The Gammer Remix EP',
    genre: 'Hardcore',
    comment: '',
    label: 'Muffin Music',
    year: '2010',
    key: '10A',
  },
  {
    title: 'Stronger (Olly P Bootleg)',
    artist: 'Arty, Mat Zo, Ray Dalton',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2017',
    key: '07B',
  },
  {
    title: 'Unfaithful',
    artist: 'Rhianna vs Technikore',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '05A',
  },
  {
    title: 'Miasma',
    artist: 'Oli G & Jessica',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '11B',
  },
  {
    title: 'Guitar Hero (Technikore Remix)',
    artist: 'Dougal & Gammer',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: '',
    year: '2011',
    key: '08A',
  },
  {
    title: 'Skycoaster',
    artist: 'Norcore',
    album: 'RuffBeatz: Audio Crysis',
    genre: 'Hands Up',
    comment: '',
    label: 'RuffBeatz',
    year: '2011',
    key: '10A',
  },
  {
    title: 'Digital Eventide',
    artist: 'Naggy',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Only Vibes Recordings',
    year: '2009',
    key: '06A',
  },
  {
    title: 'Lifeline (Extended Mix)',
    artist: 'Alan Morris & Neev Kennedy',
    album: '',
    genre: 'Trance',
    comment: '',
    label: 'Amsterdam Trance Records (RazNitzanMusic)',
    year: '2019',
    key: '08A',
  },
  {
    title: 'Atomic Orbital',
    artist: 'Mark Ashley & K-Complex',
    album: 'Nu Energy 100 - The Final Chapter',
    genre: 'Hardcore',
    comment: '',
    label: 'Nu Energy Records',
    year: '2011',
    key: '09A',
  },
  {
    title: 'Forgot The Music',
    artist: 'Dan Edge',
    album: 'Never Stop Raving: Hardcore Explosion',
    genre: 'Hardcore',
    comment: '',
    label: 'NSR Records',
    year: '2009',
    key: '08A',
  },
  {
    title: "When I'm with You (Robbie Seed Remix)",
    artist: 'Andy Elliass & ARCZI',
    album: "When I'm with You",
    genre: 'Trance',
    comment: '',
    label: 'Trance All-Stars Records',
    year: '2016',
    key: '02B',
  },
  {
    title: 'Untouchable (Scott Brown Remix)',
    artist: 'Jason UFO & Keileigh Macdonald',
    album: '',
    genre: 'Hardcore',
    comment: '',
    label: 'Ufology Digital',
    year: '2015',
    key: '09B',
  },
];

export default exampleMetadata;
